import { FeatureKey, FEATURE_KEYS } from '@/constants/feature-keys'

export const RAYYAN_FEATURES: Record<FeatureKey, boolean> = {
  [FEATURE_KEYS.AUTH]: false,
  [FEATURE_KEYS.CHAT]: true,
  [FEATURE_KEYS.LEGAL_CHAT]: false,
  [FEATURE_KEYS.ADMIN_PAGES]: true,
  [FEATURE_KEYS.ADMIN_USERS]: false,
  [FEATURE_KEYS.ADMIN_STORAGE]: true,
  [FEATURE_KEYS.ADMIN_LEGAL_STORAGE]: false,
  [FEATURE_KEYS.ADMIN_INDEXERS]: true,
  [FEATURE_KEYS.ADMIN_WEB_CRAWLER]: false,
  [FEATURE_KEYS.ADMIN_SOCIAL_MEDIA]: false,
  [FEATURE_KEYS.ADMIN_FAQ]: true,
  [FEATURE_KEYS.AI_SEARCH]: false,
  [FEATURE_KEYS.AVATAR]: true,
  [FEATURE_KEYS.VIDEO_GENERATOR]: false,
  [FEATURE_KEYS.CHAT_HISTORY]: false,
  [FEATURE_KEYS.REPORT_GENERATOR]: false,
  [FEATURE_KEYS.STATISTICS]: false,
  [FEATURE_KEYS.ADMIN_INSIGHTS]: true,
  [FEATURE_KEYS.CUSTOMER_SERVICE]: false,
  [FEATURE_KEYS.VIDEO_ANALYZER]: false,
}
