import { FEATURE_KEYS, FeatureKey } from '@/constants/feature-keys'

export const AQARAT_FEATURES: Record<FeatureKey, boolean> = {
  [FEATURE_KEYS.AUTH]: false,
  [FEATURE_KEYS.CHAT]: true,
  [FEATURE_KEYS.LEGAL_CHAT]: true,
  [FEATURE_KEYS.ADMIN_PAGES]: true,
  [FEATURE_KEYS.ADMIN_USERS]: true,
  [FEATURE_KEYS.ADMIN_STORAGE]: true,
  [FEATURE_KEYS.ADMIN_LEGAL_STORAGE]: true,
  [FEATURE_KEYS.ADMIN_INDEXERS]: true,
  [FEATURE_KEYS.ADMIN_WEB_CRAWLER]: true,
  [FEATURE_KEYS.ADMIN_SOCIAL_MEDIA]: true,
  [FEATURE_KEYS.ADMIN_FAQ]: true,
  [FEATURE_KEYS.AI_SEARCH]: true,
  [FEATURE_KEYS.AVATAR]: true,
  [FEATURE_KEYS.VIDEO_GENERATOR]: true,
  [FEATURE_KEYS.CHAT_HISTORY]: true,
  [FEATURE_KEYS.REPORT_GENERATOR]: true,
  [FEATURE_KEYS.STATISTICS]: true,
  [FEATURE_KEYS.ADMIN_INSIGHTS]: true,
  [FEATURE_KEYS.CUSTOMER_SERVICE]: true,
  [FEATURE_KEYS.VIDEO_ANALYZER]: true,
}
