import { MenuItem } from '@/contracts/menu-item-contract'
import { ALL_PERMISSIONS, PERMISSION_GROUPS } from './all-permissions'
import { ADMIN_MENU_ITEMS } from './admin-menu-items'

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    label: 'home',
    route: '/home',
    svg: 'HOME',
    permissions: [],
  },
  {
    id: 2,
    label: 'admin_services',
    route: '/home/admin',
    svg: 'SUIT_CASE',
    feature: 'admin_pages',
    imgUrl: 'assets/icons/home/admin.png',
    permissions: PERMISSION_GROUPS['ADMIN_GROUP'],
    haveSomeOfPermissions: true,
    children: ADMIN_MENU_ITEMS,
  },
  {
    id: 3,
    label: 'search',
    route: '/home/search',
    svg: 'SEARCH',
    feature: 'ai_search',
    imgUrl: 'assets/icons/home/smart-search.png',
    permissions: PERMISSION_GROUPS['SEARCH_GROUP'],
    haveSomeOfPermissions: true,
  },
  {
    id: 4,
    label: 'avatar_chat',
    route: '/home/avatar',
    svg: 'AVATAR',
    feature: 'avatar',
    imgUrl: 'assets/icons/home/chat.png',
    permissions: ['AVATAR'],
  },
  {
    id: 6,
    label: 'chat_history',
    route: '/home/chat-history',
    svg: 'HISTORY',
    feature: 'chat_history',
    permissions: PERMISSION_GROUPS['CHAT_HISTORY_GROUP'],
    haveSomeOfPermissions: true,
  },
  {
    id: 7,
    label: 'report_generator',
    route: '/home/web-crawler',
    svg: 'WEB_CRAWLER',
    feature: 'report_generator',
    permissions: PERMISSION_GROUPS['REPORT_GENERATOR_GROUP'],
  },
  {
    id: 8,
    label: 'statistics',
    route: '/home/statistics',
    svg: 'POLL',
    feature: 'statistics',
    imgUrl: 'assets/icons/home/stats.png',
    permissions: PERMISSION_GROUPS['STATISTICS_GROUP'],
    haveSomeOfPermissions: true,
  },
  {
    id: 14,
    label: 'video_generator',
    route: '/home/video-generator',
    svg: 'VIDEO_GENERATOR',
    feature: 'video_generator',
    imgUrl: 'assets/icons/home/video-generator.png',
    permissions: PERMISSION_GROUPS['VIDEO_GENERATOR_GROUP'],
    haveSomeOfPermissions: true,
  },
  {
    id: 15,
    label: 'chat',
    route: '/home',
    fragment: 'legal',
    svg: 'CHAT',
    feature: 'legal_chat',
    permissions: [ALL_PERMISSIONS.CHATBOT_LEGAL],
    haveSomeOfPermissions: true,
  },
  {
    id: 16,
    label: 'admin_insights',
    route: '/home/admin-insights',
    svg: 'CHART_INSIGHTS',
    feature: 'admin_insights',
    permissions: [],
    haveSomeOfPermissions: true,
  },
  {
    id: 17,
    label: 'customer_services',
    route: '/home/customer-services',
    svg: 'CUSTOMER_SERVICE',
    feature: 'customer_service',
    permissions: [],
    haveSomeOfPermissions: true,
  },
  {
    id: 18,
    label: 'video_analyzer',
    route: '/home/video_analyzer',
    svg: 'VIDEO_ANALYSIS',
    feature: 'video_analyzer',
    permissions: [],
    haveSomeOfPermissions: true,
  },
  // {
  //   id: 18,
  //   label: 'chat_assisstant',
  //   route: '/home',
  //   fragment: 'chat',
  //   svg: 'CHAT',
  //   feature: 'chat',
  //   permissions: [ALL_PERMISSIONS.CHATBOT],
  //   haveSomeOfPermissions: true,
  // },
]
