export const EndPoints = {
  BASE_URL: '',
  SPEECH_TOKEN: 'speech/token',
  CHAT: 'chatbot/chat',
  INTERACTIVE: 'interactive',
  INTERACTIVE_CHAT: 'chatbot/chat/interactive',
  INTERACTIVE_ACTION: 'interactive/action',
  AGENT: 'agent',
  AGENT_CHAT: 'agent/chat',
  AVATAR: 'avatar',
  LOCALS: 'http://localhost:3333',
  VIDEO_INDEXER: 'https://www.videoindexer.ai/embed',
  AI_SEARCH: 'search/search',
  CHAT_HISTORY: 'chat-history',
  DOC_INTELLIGENCE: 'document-intelligence',
  MEDIA: 'media',
  ADMIN: 'admin',
  USER: 'user',
  FAQ: 'FAQ',
  FAQ_ARCHIEVE: 'FAQ/faqs/archive',
  CHATBOT_UPLOAD_DOCUMENT: 'chatbot/upload_documents/',
  SOCIAL: 'social',
  CUSTOMER_SERVICES: 'agent/customer-service',
}

export type EndpointsType = typeof EndPoints
